version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
        auth:
          aws_access_key_id=$aws_access_key_id
          aws_secret_access_key=$aws_secret_access_key
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy --template-file template.yml --stack-name my-stack --region eu-central-1
          
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
    context: 
      - aws